# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArkusNexusTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArkusNexusTest
  pod 'Kingfisher', '~> 5.0'
  pod 'ReachabilitySwift'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 3.5'
  pod 'Cosmos', '~> 11.0'
end
